name: Build

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  schedule:
    - cron: '0 0 1 * *'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Generate fresh certificates
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          sudo snap install certbot --classic
          sudo snap set certbot trust-plugin-with-root=ok
          sudo snap install certbot-dns-cloudflare
          echo "dns_cloudflare_api_token = $CLOUDFLARE_API_TOKEN" > /tmp/cloudflare.ini
          chmod 600 /tmp/cloudflare.ini
          mkdir -p certs
          sudo certbot certonly \
            --dns-cloudflare \
            --dns-cloudflare-credentials /tmp/cloudflare.ini \
            --dns-cloudflare-propagation-seconds 60 \
            -d shared-schema.panda.st \
            --email team@pandasuite.com \
            --agree-tos \
            --non-interactive
          sudo cp /etc/letsencrypt/live/shared-schema.panda.st/privkey.pem certs/
          sudo cp /etc/letsencrypt/live/shared-schema.panda.st/fullchain.pem certs/
          sudo chown $USER:$USER certs/*.pem
      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "team@pandasuite.com"
      - name: Build
        run: npm run release
      - name: Upload certificates to release
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 'certs-${{ github.run_number }}'
          name: 'SSL Certificates ${{ github.run_number }}'
          body: |
            🔒 **Fresh SSL Certificates for shared-schema.panda.st**

            Generated: ${{ github.event.head_commit.timestamp }}
            Valid for: 90 days (Let's Encrypt standard)

            **Usage:**
            - Download `privkey.pem` and `fullchain.pem`
            - Place in your `certs/` directory  
            - Or run `npm run certs` to download automatically

            **Compatible with:** All shared-schema versions
          files: |
            certs/privkey.pem
            certs/fullchain.pem
          prerelease: false
